version: "3.8"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: filesystem
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ssdat:/var/lib/mysql
    ports:
      - 3306:3306
#      - 3305:3306
  app:
    image: filesystem/filesystem:latest
    restart: always
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/filesystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret

    ports:
      - "8080:8080"
  phpmyadmin1:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "80:80"
# permanent storage of data.
volumes:
  ssdat:
