# This file is a template, and might need editing before it works on your project.
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle

image: gradle:jdk17

stages:
  - build
  - docker

before_script:
  - cd fileSystem

build:
  stage: build
  script:
    - ./gradlew build -x test
  artifacts:
    paths:
      - fileSystem/build/libs/

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  dependencies:
    - build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t filesystem/filesystem
    - docker compose -f docker-compose.yml -p filesystem up -d
# test:
#   stage: test
#   script:
#     - ./gradlew test --tests FilesystemServiceTests

# deploy:
#   stage: deploy
#   script: echo "Define your deployment script!"
#   environment: production
